name: waymo_2d_tracking
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7

  - cudatoolkit=10.2
  - pytorch=1.5
  - torchvision=0.6

  - opencv
  - cython
  - scipy
  - scikit-learn=0.22.2
  - tqdm
  - pandas
  - pyyaml
  - scikit-image
  - shapely
  - pip
  - pip:
    - tensorboardX
    - future
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
    - git+https://github.com/NVIDIA/apex.git@1f2aa9156547377a023932a1512752c392d9bbdf
    - pretrainedmodels
    - efficientnet-pytorch
    - https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.5/detectron2-0.1.3%2Bcu102-cp37-cp37m-linux_x86_64.whl
    - pillow-simd
    - waymo-open-dataset-tf-2-1-0==1.2.0
    - ensemble-boxes
    - numba
    - filterpy
